apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-bootstrap-{{ .Values.destination.name }}
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  source:
    path: apps/networking/linkerd/resources
    repoURL: {{ .Values.platform.repository }}
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
