apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds-{{ .Values.destination.name }}
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.4.0
    helm:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      name:  tap-injector-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: authorizationpolicies.policy.linkerd.io
      jsonPointers:
        - /spec/names
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: meshtlsauthentications.policy.linkerd.io
      jsonPointers:
        - /spec/names
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: networkauthentications.policy.linkerd.io
      jsonPointers:
        - /spec/names