apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticstack
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  destination:
    namespace: elastic-system
    server: {{ .Values.destination.server }}
  source:
    repoURL: {{ .Values.platform.repository }}
    path: apps/observability/elasticstack
    targetRevision: HEAD
    helm:
      releaseName: elasticstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: elastic-operator.elastic-system.k8s.elastic.co
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle