apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
type: application
description: A Helm chart for configuration of observability on workload clusters, using an "app of apps" structure.
name: "observability"