apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  ingress:
    enabled: true
    hostname: {{ .Values.grafana.hostname }}
    tlsEnabled: true
    tlsSecretName: grafana-tls
    path: /
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: {{ .Values.grafana.adminPassword }}
    auth:
      disable_login_form: false
      disable_signout_menu: true
  dashboardLabelSelector:
    - matchExpressions:
      - key: app
        operator: In
        values:
          - grafana
  deployment:
    annotations:
      linkerd.io/inject: enabled
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi